
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: elasticsearch-operator
  name: elasticsearch-operator-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
      interval: 1s
  selector:
    matchLabels:
      name: elasticsearch-operator